#ifndef VEHICLEMENAGMENTSYSTEM_STATUSTYPE_H
#define VEHICLEMENAGMENTSYSTEM_STATUSTYPE_H

enum StatusType {
    AVAILABLE, ROAD, BROKE, REPAIR, STATUSERROR
};

#endif //VEHICLEMENAGMENTSYSTEM_STATUSTYPE_H
