#ifndef VEHICLEMENAGMENTSYSTEM_VEHICLETYPE_H
#define VEHICLEMENAGMENTSYSTEM_VEHICLETYPE_H

enum VehicleType {
    CAR,
    BUS,
    VAN,
    TRUCK,
    ANY
};

#endif //VEHICLEMENAGMENTSYSTEM_VEHICLETYPE_H
